version: '3'

services:
  app:
    container_name: minimarket-front
    image: minimarket-front:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      minimarket-network:
  
networks:
  minimarket-network:

